services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    env_file:
      - .env
    environment:
      ORACLE_PASSWORD: ${CLIENT_DB_PASSWORD}
    restart: always

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always

  product-service:
    build: ./services/product-service
    container_name: product_service
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
  

  postgres-sales:
    image: postgres:16
    container_name: postgres-sales
    ports:
    - "5432:5432"
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./services/sales-service/SalesService/Infrastructure/DataBase/schema_sales.sql:/docker-entrypoint-initdb.d/schema_sales.sql

    restart: always